# Generated by Django 4.1.5 on 2023-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tcategorias',
            fields=[
                ('categoriaid', models.AutoField(db_column='CategoriaId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=20)),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'tCategorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tclases',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=40)),
                ('horarios', models.CharField(blank=True, db_column='Horarios', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tClases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tpedidos',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, db_column='Fecha', null=True)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
            ],
            options={
                'db_table': 'tPedidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tpersona',
            fields=[
                ('idpersona', models.AutoField(db_column='IdPersona', primary_key=True, serialize=False)),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=500, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=200, null=True)),
                ('pago', models.IntegerField(blank=True, db_column='Pago', null=True)),
                ('dirección', models.CharField(blank=True, db_column='Dirección', max_length=2000, null=True)),
                ('noteléfono', models.IntegerField(blank=True, db_column='Nºteléfono', null=True)),
            ],
            options={
                'db_table': 'tPersona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tproductos',
            fields=[
                ('productosid', models.AutoField(db_column='ProductosId', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=400)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=100, null=True)),
                ('precio', models.CharField(blank=True, db_column='Precio', max_length=100, null=True)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=250)),
                ('imagen', models.CharField(blank=True, db_column='Imagen', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'tProductos',
                'managed': False,
            },
        ),
    ]
